/**
 * Canonical semantic contract for every treatment-topic button on the
 * homepage. Labels remain user-facing copy; slugs are trusted identifiers.
 * Curated navigation must never depend on fuzzy free-text classification.
 */

export const CANONICAL_PROBLEM_SLUGS = [
  "addiction",
  "anxiety",
  "communication_expression",
  "depression",
  "developmental",
  "eating_body",
  "emotional_regulation",
  "existential",
  "family_parenting",
  "grief_loss",
  "life_transitions",
  "neurodiversity",
  "ocd_compulsions",
  "performance_functioning",
  "personality_disorders",
  "relationships",
  "self_identity",
  "sexual_abuse_trauma",
  "sexuality_intimacy",
  "sleep_difficulties",
  "social_belonging",
  "somatic",
  "trauma",
  "violence_abuse",
] as const;

export type CanonicalProblemSlug = (typeof CANONICAL_PROBLEM_SLUGS)[number];

export const HOMEPAGE_PROBLEM_MAP = {
  "חרדה חברתית": ["anxiety"],
  "התקפי פאניקה": ["anxiety"],
  "חרדת בריאות": ["anxiety"],
  "פחד מטיסה": ["anxiety"],
  פוביות: ["anxiety"],
  "דאגנות יתר": ["anxiety"],
  "חרדת מבחנים": ["anxiety"],
  "מחשבות טורדניות": ["ocd_compulsions"],
  דיכאון: ["depression"],
  "מצב רוח ירוד": ["depression"],
  בדידות: ["social_belonging"],
  "חוסר מוטיבציה": ["depression"],
  "תחושת ריקנות": ["depression"],
  "קשיי שינה": ["sleep_difficulties"],
  ייאוש: ["depression"],
  "שינויים חדים במצב הרוח": ["emotional_regulation"],
  "משבר בזוגיות": ["relationships"],
  "קשיי תקשורת": ["communication_expression"],
  "פרידה וגירושין": ["relationships"],
  "קנאה וחוסר אמון": ["relationships"],
  "אינטימיות ומיניות": ["sexuality_intimacy"],
  "קושי ביצירת קשר": ["relationships"],
  "תלות רגשית": ["relationships"],
  "מערכות יחסים פוגעניות": ["violence_abuse"],
  "פוסט טראומה": ["trauma"],
  "אובדן ואבל": ["grief_loss"],
  "משבר אישי": ["life_transitions"],
  "מחלה או פציעה": ["somatic"],
  "פגיעה מינית": ["sexual_abuse_trauma"],
  אלימות: ["violence_abuse"],
  "שינוי משמעותי בחיים": ["life_transitions"],
  "התמודדות לאחר אירוע ביטחוני": ["trauma"],
  "קשיים חברתיים": ["social_belonging"],
  "התפרצויות זעם": ["emotional_regulation"],
  "הדרכת הורים": ["family_parenting"],
  "קשיי הסתגלות": ["life_transitions"],
  "פחדים אצל ילדים": ["anxiety"],
  "יחסים בין אחים": ["family_parenting"],
  "גירושי הורים": ["family_parenting"],
  "קשיים בבית הספר": ["developmental"],
  "שחיקה בעבודה": ["performance_functioning"],
  "לחץ בעבודה": ["performance_functioning"],
  דחיינות: ["performance_functioning"],
  "קשיי ריכוז": ["neurodiversity"],
  "בחירת קריירה": ["performance_functioning"],
  "חוסר ביטחון מקצועי": ["performance_functioning"],
  "איזון בין עבודה לחיים": ["performance_functioning"],
  "דימוי עצמי נמוך": ["self_identity"],
  "חוסר ביטחון": ["self_identity"],
  "קושי בהצבת גבולות": ["self_identity"],
  "ריצוי אחרים": ["self_identity"],
  "קבלת החלטות": ["self_identity"],
  "משבר זהות": ["self_identity"],
  "תחושת תקיעות": ["life_transitions"],
  "התפתחות אישית": ["self_identity"],
  "אכילה רגשית": ["eating_body"],
  "הפרעות אכילה": ["eating_body"],
  "דימוי גוף": ["eating_body"],
  התמכרויות: ["addiction"],
  עישון: ["addiction"],
  "שימוש באלכוהול": ["addiction"],
  "הרגלים כפייתיים": ["addiction"],
  "קושי בשינוי הרגלים": ["addiction"],
  "קשיי אכילה": ["eating_body"],
  "קשיי פרידה": ["anxiety"],
  "ויסות רגשי": ["emotional_regulation"],
  "עיכוב התפתחותי": ["developmental"],
  "התפרצויות והתנהגות מאתגרת": ["emotional_regulation"],
  "הסתגלות למסגרת": ["developmental"],
  "חרדה ופחדים": ["anxiety"],
  "קשיי קשב וריכוז": ["neurodiversity"],
  "התפרצויות וכעסים": ["emotional_regulation"],
  "התמודדות עם גירושי הורים": ["family_parenting"],
  "דימוי עצמי": ["self_identity"],
  "דיכאון ושינויים במצב הרוח": ["depression"],
  "קשיים חברתיים ובדידות": ["social_belonging"],
  "יחסים עם ההורים": ["family_parenting"],
  "לחץ לימודי": ["performance_functioning"],
  "חרדה ולחץ": ["anxiety"],
  "זוגיות ומערכות יחסים": ["relationships"],
  "לימודים וקריירה": ["performance_functioning"],
  "זהות וכיוון בחיים": ["self_identity"],
  "בדידות וקשיים חברתיים": ["social_belonging"],
  "פרידות ומשברים": ["relationships", "life_transitions"],
  "עצמאות ומעבר לחיים בוגרים": ["life_transitions"],
  "חרדה ודאגנות": ["anxiety"],
  "דיכאון ומצב רוח ירוד": ["depression"],
  "שחיקה ולחץ בעבודה": ["performance_functioning"],
  "משברים אישיים": ["life_transitions"],
  "קשיים בזוגיות": ["relationships"],
  "טראומה ואובדן": ["trauma", "grief_loss"],
  "שינויי חיים": ["life_transitions"],
  "דיכאון וחרדה": ["depression", "anxiety"],
  "הסתגלות לפרישה": ["life_transitions"],
  "שינויים בריאותיים": ["somatic"],
  "ירידה בתפקוד": ["somatic"],
  "יחסים במשפחה": ["family_parenting"],
  "משמעות ואיכות חיים": ["existential"],
  "בגידה ואובדן אמון": ["relationships"],
  "קונפליקטים חוזרים": ["relationships"],
  "הורות משותפת": ["family_parenting"],
  "הכנה לנישואין": ["relationships"],
  "יחסי הורים וילדים": ["family_parenting"],
  "מריבות וקונפליקטים במשפחה": ["family_parenting"],
  "קשיים בין אחים": ["family_parenting"],
  "גירושין ומשפחה בתהליך שינוי": ["family_parenting", "relationships"],
  "משפחות משולבות": ["family_parenting"],
  "התמודדות עם ילד במשבר": ["family_parenting"],
  "טיפול משפחתי": ["family_parenting"],
} as const satisfies Record<string, readonly CanonicalProblemSlug[]>;

export function homepageProblemSlugs(label: string): readonly CanonicalProblemSlug[] {
  return HOMEPAGE_PROBLEM_MAP[label as keyof typeof HOMEPAGE_PROBLEM_MAP] ?? [];
}
