/**
 * Canonical semantic contract for every treatment-topic button on the
 * homepage. Labels remain user-facing copy; slugs are trusted identifiers.
 * Curated navigation must never depend on fuzzy free-text classification.
 *
 * This list mirrors the 62 active canonical treatment domains in the DB.
 * UX groups on the homepage are navigation only; they are not ontology parents.
 */

export const CANONICAL_PROBLEM_SLUGS = [
  "anxiety",
  "depression",
  "ocd_compulsions",
  "emotional_regulation",
  "self_identity",
  "personality_disorders",
  "bipolar_disorder",
  "psychosis",
  "existential",
  "trauma",
  "sexual_abuse_trauma",
  "violence_abuse",
  "grief_loss",
  "life_transitions",
  "relationships",
  "family_parenting",
  "social_belonging",
  "communication_expression",
  "sexuality_intimacy",
  "adhd",
  "autism",
  "childhood_development",
  "sensory_processing",
  "behavioral_challenges",
  "learning_difficulties",
  "motor_coordination",
  "language_communication",
  "speech_articulation",
  "fluency_stuttering",
  "voice",
  "hearing_auditory_rehabilitation",
  "swallowing_feeding",
  "performance_functioning",
  "burnout",
  "career_direction",
  "eating_disorders",
  "body_image",
  "nutrition_eating_habits",
  "medical_nutrition",
  "sleep_difficulties",
  "musculoskeletal_pain",
  "chronic_pain",
  "orthopedic_rehabilitation",
  "neurological_rehabilitation",
  "mobility_balance",
  "pelvic_floor",
  "cardiopulmonary_rehabilitation",
  "sports_rehabilitation",
  "daily_functioning",
  "cognitive_rehabilitation",
  "fine_motor_graphomotor",
  "cognitive_decline_dementia",
  "pregnancy_birth_postpartum",
  "breastfeeding_lactation",
  "fertility_journey",
  "addiction",
  "substance_use",
  "behavioral_addiction",
  "somatic",
  "chronic_illness_adjustment",
  "medical_rehabilitation",
  "disability_adjustment",
] as const;

export type CanonicalProblemSlug = (typeof CANONICAL_PROBLEM_SLUGS)[number];

/**
 * Explicit mappings for the 109 curated homepage topic buttons.
 *
 * A broad UI label may intentionally map to more than one canonical domain.
 * Unified Search treats these as trusted semantic signals and gates on overlap,
 * so a therapist may match any relevant mapped domain while matching multiple
 * domains improves semantic score.
 */
export const HOMEPAGE_PROBLEM_MAP = {
  "חרדה חברתית": ["anxiety"],
  "התקפי פאניקה": ["anxiety"],
  "חרדת בריאות": ["anxiety"],
  "פחד מטיסה": ["anxiety"],
  פוביות: ["anxiety"],
  "דאגנות יתר": ["anxiety"],
  "חרדת מבחנים": ["anxiety"],
  "מחשבות טורדניות": ["ocd_compulsions"],
  דיכאון: ["depression"],
  "מצב רוח ירוד": ["depression"],
  בדידות: ["social_belonging"],
  "חוסר מוטיבציה": ["depression"],
  "תחושת ריקנות": ["depression"],
  "קשיי שינה": ["sleep_difficulties"],
  ייאוש: ["depression"],
  "שינויים חדים במצב הרוח": ["emotional_regulation"],
  "משבר בזוגיות": ["relationships"],
  "קשיי תקשורת": ["communication_expression"],
  "פרידה וגירושין": ["relationships"],
  "קנאה וחוסר אמון": ["relationships"],
  "אינטימיות ומיניות": ["sexuality_intimacy"],
  "קושי ביצירת קשר": ["relationships"],
  "תלות רגשית": ["relationships"],
  "מערכות יחסים פוגעניות": ["violence_abuse"],
  "פוסט טראומה": ["trauma"],
  "אובדן ואבל": ["grief_loss"],
  "משבר אישי": ["life_transitions"],
  "מחלה או פציעה": ["chronic_illness_adjustment"],
  "פגיעה מינית": ["sexual_abuse_trauma"],
  אלימות: ["violence_abuse"],
  "שינוי משמעותי בחיים": ["life_transitions"],
  "התמודדות לאחר אירוע ביטחוני": ["trauma"],
  "קשיים חברתיים": ["social_belonging"],
  "התפרצויות זעם": ["emotional_regulation"],
  "הדרכת הורים": ["family_parenting"],
  "קשיי הסתגלות": ["life_transitions"],
  "פחדים אצל ילדים": ["anxiety"],
  "יחסים בין אחים": ["family_parenting"],
  "גירושי הורים": ["family_parenting"],
  "קשיים בבית הספר": ["performance_functioning", "learning_difficulties"],
  "שחיקה בעבודה": ["burnout"],
  "לחץ בעבודה": ["burnout"],
  דחיינות: ["performance_functioning"],
  "קשיי ריכוז": ["performance_functioning"],
  "בחירת קריירה": ["career_direction"],
  "חוסר ביטחון מקצועי": ["performance_functioning"],
  "איזון בין עבודה לחיים": ["burnout"],
  "דימוי עצמי נמוך": ["self_identity"],
  "חוסר ביטחון": ["self_identity"],
  "קושי בהצבת גבולות": ["self_identity"],
  "ריצוי אחרים": ["self_identity"],
  "קבלת החלטות": ["self_identity"],
  "משבר זהות": ["self_identity"],
  "תחושת תקיעות": ["life_transitions"],
  "התפתחות אישית": ["self_identity"],
  "אכילה רגשית": ["nutrition_eating_habits"],
  "הפרעות אכילה": ["eating_disorders"],
  "דימוי גוף": ["body_image"],
  התמכרויות: ["addiction"],
  עישון: ["substance_use"],
  "שימוש באלכוהול": ["substance_use"],
  "הרגלים כפייתיים": ["behavioral_addiction", "ocd_compulsions"],
  "קושי בשינוי הרגלים": ["addiction"],
  "קשיי אכילה": ["swallowing_feeding"],
  "קשיי פרידה": ["anxiety"],
  "ויסות רגשי": ["emotional_regulation"],
  "עיכוב התפתחותי": ["childhood_development"],
  "התפרצויות והתנהגות מאתגרת": ["behavioral_challenges"],
  "הסתגלות למסגרת": ["childhood_development", "life_transitions"],
  "חרדה ופחדים": ["anxiety"],
  "קשיי קשב וריכוז": ["adhd"],
  "התפרצויות וכעסים": ["emotional_regulation"],
  "התמודדות עם גירושי הורים": ["family_parenting"],
  "דימוי עצמי": ["self_identity"],
  "דיכאון ושינויים במצב הרוח": ["depression"],
  "קשיים חברתיים ובדידות": ["social_belonging"],
  "יחסים עם ההורים": ["family_parenting"],
  "לחץ לימודי": ["performance_functioning"],
  "חרדה ולחץ": ["anxiety"],
  "זוגיות ומערכות יחסים": ["relationships"],
  "לימודים וקריירה": ["performance_functioning", "career_direction"],
  "זהות וכיוון בחיים": ["self_identity", "existential"],
  "בדידות וקשיים חברתיים": ["social_belonging"],
  "פרידות ומשברים": ["relationships", "life_transitions"],
  "עצמאות ומעבר לחיים בוגרים": ["life_transitions"],
  "חרדה ודאגנות": ["anxiety"],
  "דיכאון ומצב רוח ירוד": ["depression"],
  "שחיקה ולחץ בעבודה": ["burnout"],
  "משברים אישיים": ["life_transitions"],
  "קשיים בזוגיות": ["relationships"],
  "טראומה ואובדן": ["trauma", "grief_loss"],
  "שינויי חיים": ["life_transitions"],
  "דיכאון וחרדה": ["depression", "anxiety"],
  "הסתגלות לפרישה": ["life_transitions"],
  "שינויים בריאותיים": ["chronic_illness_adjustment"],
  "ירידה בתפקוד": ["daily_functioning"],
  "יחסים במשפחה": ["family_parenting"],
  "משמעות ואיכות חיים": ["existential"],
  "בגידה ואובדן אמון": ["relationships"],
  "קונפליקטים חוזרים": ["relationships"],
  "הורות משותפת": ["family_parenting"],
  "הכנה לנישואין": ["relationships"],
  "יחסי הורים וילדים": ["family_parenting"],
  "מריבות וקונפליקטים במשפחה": ["family_parenting"],
  "קשיים בין אחים": ["family_parenting"],
  "גירושין ומשפחה בתהליך שינוי": ["family_parenting", "relationships"],
  "משפחות משולבות": ["family_parenting"],
  "התמודדות עם ילד במשבר": ["family_parenting"],
  "טיפול משפחתי": ["family_parenting"],
} as const satisfies Record<string, readonly CanonicalProblemSlug[]>;

export function homepageProblemSlugs(label: string): readonly CanonicalProblemSlug[] {
  return HOMEPAGE_PROBLEM_MAP[label as keyof typeof HOMEPAGE_PROBLEM_MAP] ?? [];
}
