/**
 * Test-support snapshot of the canonical treatment-domain catalog after
 * Tipulinks Migration 1 + Migration 2 (2026-08-16).
 *
 * Test-only synthetic IDs are the canonical sort_order values 1..62;
 * production matching only relies on the internal problem_id -> slug relation.
 * Counts: 62 active problems, 483 unique aliases.
 */
import type { FeedbackCatalog } from "../profile-domain-feedback";

export const LIVE_ACTIVE_CATALOG: FeedbackCatalog = {
  problems: [
    { id: "1", slug: "anxiety", name_he: "חרדה ופחדים" },
    { id: "2", slug: "depression", name_he: "דיכאון ומצב רוח ירוד" },
    { id: "3", slug: "ocd_compulsions", name_he: "OCD ומחשבות או התנהגויות כפייתיות" },
    { id: "4", slug: "emotional_regulation", name_he: "ויסות רגשי, כעס והצפה" },
    { id: "5", slug: "self_identity", name_he: "דימוי עצמי, ערך עצמי וזהות" },
    { id: "6", slug: "personality_disorders", name_he: "הפרעות אישיות" },
    { id: "7", slug: "bipolar_disorder", name_he: "הפרעה דו־קוטבית" },
    { id: "8", slug: "psychosis", name_he: "פסיכוזה והפרעות פסיכוטיות" },
    { id: "9", slug: "existential", name_he: "שאלות קיום, משמעות וכיוון בחיים" },
    { id: "10", slug: "trauma", name_he: "טראומה ופוסט־טראומה" },
    { id: "11", slug: "sexual_abuse_trauma", name_he: "פגיעות מיניות וטראומה מינית" },
    { id: "12", slug: "violence_abuse", name_he: "אלימות ומערכות יחסים פוגעניות" },
    { id: "13", slug: "grief_loss", name_he: "אבל, אובדן ושכול" },
    { id: "14", slug: "life_transitions", name_he: "מעברי חיים והסתגלות" },
    { id: "15", slug: "relationships", name_he: "זוגיות והיקשרות" },
    { id: "16", slug: "family_parenting", name_he: "משפחה והורות" },
    { id: "17", slug: "social_belonging", name_he: "בדידות, שייכות וקשרים חברתיים" },
    { id: "18", slug: "communication_expression", name_he: "תקשורת בין־אישית וביטוי רגשי" },
    { id: "19", slug: "sexuality_intimacy", name_he: "מיניות ואינטימיות" },
    { id: "20", slug: "adhd", name_he: "קשב, ADHD ותפקודים ניהוליים" },
    { id: "21", slug: "autism", name_he: "אוטיזם והספקטרום האוטיסטי" },
    { id: "22", slug: "childhood_development", name_he: "עיכובים וקשיים התפתחותיים" },
    { id: "23", slug: "sensory_processing", name_he: "ויסות ועיבוד חושי" },
    { id: "24", slug: "behavioral_challenges", name_he: "התנהגות מאתגרת וקשיי התנהגות" },
    { id: "25", slug: "learning_difficulties", name_he: "לקויות וקשיי למידה" },
    { id: "26", slug: "motor_coordination", name_he: "קואורדינציה והתפתחות מוטורית" },
    { id: "27", slug: "language_communication", name_he: "שפה ותקשורת" },
    { id: "28", slug: "speech_articulation", name_he: "דיבור והיגוי" },
    { id: "29", slug: "fluency_stuttering", name_he: "שטף דיבור וגמגום" },
    { id: "30", slug: "voice", name_he: "קול" },
    { id: "31", slug: "hearing_auditory_rehabilitation", name_he: "שמיעה ושיקום שמיעתי" },
    { id: "32", slug: "swallowing_feeding", name_he: "בליעה, לעיסה ואכילה תפקודית" },
    { id: "33", slug: "performance_functioning", name_he: "תפקוד בעבודה ובלימודים" },
    { id: "34", slug: "burnout", name_he: "שחיקה ולחץ תעסוקתי" },
    { id: "35", slug: "career_direction", name_he: "בחירת קריירה ושינוי מקצועי" },
    { id: "36", slug: "eating_disorders", name_he: "הפרעות אכילה" },
    { id: "37", slug: "body_image", name_he: "דימוי גוף" },
    { id: "38", slug: "nutrition_eating_habits", name_he: "תזונה והרגלי אכילה" },
    { id: "39", slug: "medical_nutrition", name_he: "תזונה במצבים רפואיים" },
    { id: "40", slug: "sleep_difficulties", name_he: "קשיי שינה" },
    { id: "41", slug: "musculoskeletal_pain", name_he: "כאב וקשיי שריר־שלד" },
    { id: "42", slug: "chronic_pain", name_he: "כאב כרוני" },
    { id: "43", slug: "orthopedic_rehabilitation", name_he: "שיקום אורתופדי ולאחר פציעה או ניתוח" },
    { id: "44", slug: "neurological_rehabilitation", name_he: "שיקום נוירולוגי" },
    { id: "45", slug: "mobility_balance", name_he: "ניידות, שיווי משקל, סחרחורת ומניעת נפילות" },
    { id: "46", slug: "pelvic_floor", name_he: "רצפת אגן" },
    { id: "47", slug: "cardiopulmonary_rehabilitation", name_he: "שיקום לב־ריאה ונשימה" },
    { id: "48", slug: "sports_rehabilitation", name_he: "פציעות ספורט וחזרה לפעילות" },
    { id: "49", slug: "daily_functioning", name_he: "תפקוד יומיומי ועצמאות" },
    { id: "50", slug: "cognitive_rehabilitation", name_he: "שיקום קוגניטיבי" },
    { id: "51", slug: "fine_motor_graphomotor", name_he: "מוטוריקה עדינה וגרפומוטוריקה" },
    { id: "52", slug: "cognitive_decline_dementia", name_he: "ירידה קוגניטיבית ודמנציה" },
    { id: "53", slug: "pregnancy_birth_postpartum", name_he: "היריון, לידה ומשכב לידה" },
    { id: "54", slug: "breastfeeding_lactation", name_he: "הנקה" },
    { id: "55", slug: "fertility_journey", name_he: "ליווי סביב פוריות" },
    { id: "56", slug: "addiction", name_he: "התמכרויות ותלות" },
    { id: "57", slug: "substance_use", name_he: "שימוש בחומרים והתמכרויות לחומרים" },
    { id: "58", slug: "behavioral_addiction", name_he: "התמכרויות התנהגותיות" },
    { id: "59", slug: "somatic", name_he: "תסמינים פסיכוסומטיים וקשר גוף־נפש" },
    { id: "60", slug: "chronic_illness_adjustment", name_he: "התמודדות עם מחלה כרונית או מצב רפואי" },
    { id: "61", slug: "medical_rehabilitation", name_he: "שיקום לאחר מחלה, אשפוז או ניתוח" },
    { id: "62", slug: "disability_adjustment", name_he: "הסתגלות למוגבלות ולשינוי תפקודי" },
  ],
  aliases: [
    { problem_id: "1", alias: "אני חרד" },
    { problem_id: "1", alias: "אני מפחד כל הזמן" },
    { problem_id: "1", alias: "אני נמנע מדברים בגלל פחד" },
    { problem_id: "2", alias: "אני בדיכאון" },
    { problem_id: "2", alias: "אני לא נהנה מכלום" },
    { problem_id: "2", alias: "כלום לא מעניין אותי" },
    { problem_id: "15", alias: "יש לי בעיות בזוגיות" },
    { problem_id: "15", alias: "קשה לי במערכות יחסים" },
    { problem_id: "15", alias: "אני מפחד להיקשר" },
    { problem_id: "15", alias: "קשה לי לסמוך על אנשים" },
    { problem_id: "13", alias: "אני מתמודד עם אובדן" },
    { problem_id: "13", alias: "איבדתי מישהו קרוב" },
    { problem_id: "13", alias: "אני מתאבל" },
    { problem_id: "13", alias: "משהו בי נשבר מאז שאיבדתי מישהו" },
    { problem_id: "14", alias: "אני בתקופה של שינוי גדול" },
    { problem_id: "14", alias: "עברתי שינוי בחיים ואני לא מסתדר" },
    { problem_id: "14", alias: "אני לא מוצא את עצמי אחרי מעבר" },
    { problem_id: "14", alias: "קשה לי להסתגל למצב חדש" },
    { problem_id: "14", alias: "אני בין שלבים בחיים ולא יציב" },
    { problem_id: "20", alias: "יש לי ADHD" },
    { problem_id: "3", alias: "יש לי מחשבות טורדניות" },
    { problem_id: "3", alias: "אני חייב לעשות דברים שוב ושוב" },
    { problem_id: "3", alias: "יש לי טקסים שאני חייב לבצע" },
    { problem_id: "3", alias: "אני בודק דברים כל הזמן" },
    { problem_id: "56", alias: "יש לי התמכרות" },
    { problem_id: "56", alias: "קשה לי לשלוט בשימוש" },
    { problem_id: "37", alias: "אני לא מרוצה מהגוף שלי" },
    { problem_id: "37", alias: "קשה לי עם דימוי גוף" },
    { problem_id: "17", alias: "אני מרגיש לא שייך" },
    { problem_id: "17", alias: "קשה לי להתחבר לאנשים" },
    { problem_id: "17", alias: "אני לבד חברתית" },
    { problem_id: "17", alias: "אין לי חברים קרובים" },
    { problem_id: "17", alias: "אני מחוץ לקבוצה" },
    { problem_id: "17", alias: "אני לא מצליח להשתלב" },
    { problem_id: "5", alias: "אני לא יודע מי אני" },
    { problem_id: "5", alias: "אני מבולבל לגבי עצמי" },
    { problem_id: "5", alias: "אני לא בטוח בזהות שלי" },
    { problem_id: "9", alias: "אין משמעות למה שאני עושה" },
    { problem_id: "9", alias: "אני לא מוצא משמעות" },
    { problem_id: "20", alias: "יש לי ADHD או חשד לזה" },
    { problem_id: "13", alias: "התאבלות" },
    { problem_id: "13", alias: "אבא שלי נפטר" },
    { problem_id: "13", alias: "אמא שלי נפטרה" },
    { problem_id: "13", alias: "אני מתאבלת" },
    { problem_id: "13", alias: "קשה לי אחרי המוות" },
    { problem_id: "17", alias: "בודד" },
    { problem_id: "17", alias: "בודדה" },
    { problem_id: "17", alias: "אני בודד" },
    { problem_id: "17", alias: "אני בודדה" },
    { problem_id: "17", alias: "אני מרגיש בודד" },
    { problem_id: "17", alias: "אני מרגישה בודדה" },
    { problem_id: "17", alias: "תחושת בדידות" },
    { problem_id: "17", alias: "אין לי חברים" },
    { problem_id: "17", alias: "אין לי עם מי לדבר" },
    { problem_id: "1", alias: "פאניקה" },
    { problem_id: "1", alias: "אטאק" },
    { problem_id: "1", alias: "אטאקים" },
    { problem_id: "1", alias: "התקפי חרדה" },
    { problem_id: "1", alias: "התקף חרדה" },
    { problem_id: "10", alias: "פוסט-טראומה" },
    { problem_id: "10", alias: "פלאשבק" },
    { problem_id: "10", alias: "היפר עוררות" },
    { problem_id: "10", alias: "טראמה" },
    { problem_id: "10", alias: "טראומה" },
    { problem_id: "10", alias: "טראומטי" },
    { problem_id: "10", alias: "חוויה טראומטית" },
    { problem_id: "34", alias: "שחיקה" },
    { problem_id: "34", alias: "שחיקה מהעבודה" },
    { problem_id: "34", alias: "אני שחוק" },
    { problem_id: "34", alias: "אני שחוקה" },
    { problem_id: "4", alias: "כועס" },
    { problem_id: "4", alias: "כועסת" },
    { problem_id: "4", alias: "אני כועס" },
    { problem_id: "4", alias: "אני כועסת" },
    { problem_id: "4", alias: "אני מתפרץ" },
    { problem_id: "4", alias: "כעסים" },
    { problem_id: "1", alias: "פחד חברתי" },
    { problem_id: "1", alias: "פחד מאנשים" },
    { problem_id: "1", alias: "פוחד ממצבים חברתיים" },
    { problem_id: "1", alias: "פוחדת מלדבר בפני קהל" },
    { problem_id: "1", alias: "בושה חברתית" },
    { problem_id: "1", alias: "חרדה מפני אנשים" },
    { problem_id: "5", alias: "אין לי ערך" },
    { problem_id: "5", alias: "אני לא שווה" },
    { problem_id: "5", alias: "כולם טובים ממני" },
    { problem_id: "5", alias: "אני שונאת את עצמי" },
    { problem_id: "5", alias: "אני לא סובלת את עצמי" },
    { problem_id: "5", alias: "אני שונא את עצמי" },
    { problem_id: "5", alias: "אני לא מאמין בעצמי" },
    { problem_id: "15", alias: "משבר בזוגיות" },
    { problem_id: "15", alias: "מריבות בזוגיות" },
    { problem_id: "15", alias: "לא מסתדרים בזוגיות" },
    { problem_id: "15", alias: "לא מסתדרת עם בן הזוג" },
    { problem_id: "15", alias: "לא מסתדר עם בת הזוג" },
    { problem_id: "15", alias: "בגידה בזוגיות" },
    { problem_id: "15", alias: "בגד בי" },
    { problem_id: "15", alias: "בגדה בי" },
    { problem_id: "15", alias: "כועסת על בן הזוג" },
    { problem_id: "15", alias: "בעל שלי מוציא אותי מדעתי" },
    { problem_id: "4", alias: "אני מוצף" },
    { problem_id: "4", alias: "אני מוצפת" },
    { problem_id: "19", alias: "בעיות אינטימיות" },
    { problem_id: "19", alias: "קושי באינטימיות" },
    { problem_id: "19", alias: "לא מצליח להיות אינטימי" },
    { problem_id: "19", alias: "לא מצליחה להיות אינטימית" },
    { problem_id: "37", alias: "דימוי גוף נמוך" },
    { problem_id: "37", alias: "לא אוהבת את הגוף שלי" },
    { problem_id: "37", alias: "לא אוהב את הגוף שלי" },
    { problem_id: "37", alias: "שונא את הגוף שלי" },
    { problem_id: "37", alias: "שונאת את הגוף שלי" },
    { problem_id: "16", alias: "לחץ הורי" },
    { problem_id: "16", alias: "שחיקת הורים" },
    { problem_id: "16", alias: "קושי בהורות" },
    { problem_id: "16", alias: "לא יודעת איך להתמודד עם הילדים" },
    { problem_id: "16", alias: "לא יודע איך להתמודד עם הילדים" },
    { problem_id: "16", alias: "מתקשה להורות" },
    { problem_id: "16", alias: "אני מתפרצת על הילדים" },
    { problem_id: "16", alias: "אני מתפרץ על הילדים" },
    { problem_id: "57", alias: "אלכוהול" },
    { problem_id: "57", alias: "שתייה מופרזת" },
    { problem_id: "57", alias: "קנביס" },
    { problem_id: "57", alias: "אני שותה יותר מדי" },
    { problem_id: "57", alias: "אני משתמש בסמים" },
    { problem_id: "57", alias: "שימוש לרעה באלכוהול" },
    { problem_id: "57", alias: "התמכרות לאלכוהול" },
    { problem_id: "57", alias: "התמכרות לסמים" },
    { problem_id: "2", alias: "בדאון" },
    { problem_id: "2", alias: "אני בדאון" },
    { problem_id: "2", alias: "מצב רוח ירוד" },
    { problem_id: "2", alias: "אני בדאון רציני" },
    { problem_id: "2", alias: "אני בעצב" },
    { problem_id: "1", alias: "היפוכונדריה" },
    { problem_id: "14", alias: "מעבר בחיים" },
    { problem_id: "14", alias: "שינוי גדול בחיים" },
    { problem_id: "14", alias: "שינוי משמעותי" },
    { problem_id: "14", alias: "נקודת מפנה" },
    { problem_id: "5", alias: "לא יודעת מי אני" },
    { problem_id: "5", alias: "לא יודע מי אני" },
    { problem_id: "59", alias: "פסיכוסומטי" },
    { problem_id: "59", alias: "כאבי בטן מלחץ" },
    { problem_id: "59", alias: "כאב ראש מלחץ" },
    { problem_id: "10", alias: "פגיעה בילדות" },
    { problem_id: "10", alias: "התעללות בילדות" },
    { problem_id: "10", alias: "אלימות בילדות" },
    { problem_id: "10", alias: "נפגעתי בילדות" },
    { problem_id: "15", alias: "בעיות אמון" },
    { problem_id: "15", alias: "קשה לי לסמוך" },
    { problem_id: "15", alias: "לא סומכת יותר" },
    { problem_id: "15", alias: "לא סומך על אף אחד" },
    { problem_id: "15", alias: "אחרי בגידה קשה לסמוך" },
    { problem_id: "15", alias: "חוסר אמון" },
    { problem_id: "2", alias: "הכול אפור" },
    { problem_id: "10", alias: "חוויות טראומטיות" },
    { problem_id: "1", alias: "חרדות" },
    { problem_id: "5", alias: "קשיים בדימוי העצמי" },
    { problem_id: "1", alias: "הפרעת חרדה" },
    { problem_id: "14", alias: "משברי חיים" },
    { problem_id: "1", alias: "דאגנות יתר" },
    { problem_id: "13", alias: "אבל ושכול" },
    { problem_id: "3", alias: "OCD" },
    { problem_id: "2", alias: "דיכאונות" },
    { problem_id: "3", alias: "הפרעה טורדנית כפייתית" },
    { problem_id: "14", alias: "משבר חיים" },
    { problem_id: "16", alias: "הדרכת הורים" },
    { problem_id: "5", alias: "ביטחון עצמי נמוך" },
    { problem_id: "13", alias: "התמודדות עם אובדן" },
    { problem_id: "3", alias: "טורדנות כפייתית" },
    { problem_id: "3", alias: "הפרעה אובססיבית קומפולסיבית" },
    { problem_id: "13", alias: "התמודדות עם אבל" },
    { problem_id: "10", alias: "PTSD" },
    { problem_id: "1", alias: "הפרעות חרדה" },
    { problem_id: "10", alias: "פוסט טראומה" },
    { problem_id: "13", alias: "תהליך אבל" },
    { problem_id: "58", alias: "התנהגות ממכרת" },
    { problem_id: "5", alias: "דימוי עצמי" },
    { problem_id: "16", alias: "ייעוץ להורים" },
    { problem_id: "5", alias: "ערך עצמי נמוך" },
    { problem_id: "3", alias: "מחשבות טורדניות" },
    { problem_id: "16", alias: "הדרכה הורית" },
    { problem_id: "3", alias: "מחשבות כפייתיות" },
    { problem_id: "1", alias: "חרדה" },
    { problem_id: "2", alias: "דיכאון" },
    { problem_id: "13", alias: "אובדן אדם קרוב" },
    { problem_id: "16", alias: "תמיכה הורית" },
    { problem_id: "2", alias: "תסמיני דיכאון" },
    { problem_id: "16", alias: "ליווי הורים" },
    { problem_id: "2", alias: "מצב דיכאוני" },
    { problem_id: "10", alias: "טראומה נפשית" },
    { problem_id: "56", alias: "התמכרויות" },
    { problem_id: "5", alias: "דימוי עצמי נמוך" },
    { problem_id: "14", alias: "משברים בחיים" },
    { problem_id: "10", alias: "הפרעה פוסט טראומטית" },
    { problem_id: "10", alias: "אירוע טראומטי" },
    { problem_id: "5", alias: "חוסר ביטחון עצמי" },
    { problem_id: "56", alias: "התמכרות" },
    { problem_id: "15", alias: "פרידה זוגית" },
    { problem_id: "4", alias: "התפרצויות זעם" },
    { problem_id: "11", alias: "פגיעות מיניות" },
    { problem_id: "16", alias: "יחסי הורים וילדים" },
    { problem_id: "11", alias: "תקיפה מינית" },
    { problem_id: "15", alias: "משבר זוגי" },
    { problem_id: "6", alias: "הפרעת אישיות" },
    { problem_id: "15", alias: "קשיים בזוגיות" },
    { problem_id: "3", alias: "טקסים כפייתיים" },
    { problem_id: "1", alias: "פוביות" },
    { problem_id: "11", alias: "נפגעי תקיפה מינית" },
    { problem_id: "5", alias: "משבר זהות" },
    { problem_id: "1", alias: "חרדה מוכללת" },
    { problem_id: "37", alias: "קשיים בדימוי הגוף" },
    { problem_id: "1", alias: "חרדה חברתית" },
    { problem_id: "17", alias: "תחושת חוסר שייכות" },
    { problem_id: "1", alias: "התקף פאניקה" },
    { problem_id: "10", alias: "C-PTSD" },
    { problem_id: "10", alias: "טראומה בילדות" },
    { problem_id: "34", alias: "תחושת שחיקה" },
    { problem_id: "16", alias: "קשיים ביחסי הורים וילדים" },
    { problem_id: "17", alias: "קושי ביצירת קשרים חברתיים" },
    { problem_id: "4", alias: "ויסות רגשי" },
    { problem_id: "11", alias: "התעללות מינית" },
    { problem_id: "1", alias: "התקפי פאניקה" },
    { problem_id: "5", alias: "קשיים בזהות העצמית" },
    { problem_id: "37", alias: "דימוי גוף שלילי" },
    { problem_id: "10", alias: "CPTSD" },
    { problem_id: "36", alias: "בולימיה" },
    { problem_id: "3", alias: "התנהגויות כפייתיות" },
    { problem_id: "20", alias: "הפרעת קשב וריכוז" },
    { problem_id: "10", alias: "טראומה מורכבת" },
    { problem_id: "4", alias: "הצפה רגשית" },
    { problem_id: "5", alias: "זהות עצמית" },
    { problem_id: "21", alias: "ספקטרום אוטיסטי" },
    { problem_id: "1", alias: "פוביה" },
    { problem_id: "11", alias: "פגיעה מינית" },
    { problem_id: "3", alias: "טקס כפייתי" },
    { problem_id: "4", alias: "קושי בשליטה בכעסים" },
    { problem_id: "1", alias: "הפרעת חרדה מוכללת" },
    { problem_id: "21", alias: "אוטיזם" },
    { problem_id: "3", alias: "התנהגות כפייתית" },
    { problem_id: "6", alias: "הפרעות אישיות" },
    { problem_id: "17", alias: "חוסר שייכות" },
    { problem_id: "34", alias: "שחיקה בעבודה" },
    { problem_id: "1", alias: "חרדת בריאות" },
    { problem_id: "11", alias: "נפגעות תקיפה מינית" },
    { problem_id: "20", alias: "ADHD" },
    { problem_id: "5", alias: "קשיי זהות" },
    { problem_id: "10", alias: "טראומת ילדות" },
    { problem_id: "36", alias: "אנורקסיה" },
    { problem_id: "34", alias: "שחיקה מקצועית" },
    { problem_id: "4", alias: "קשיים בשליטה בכעסים" },
    { problem_id: "15", alias: "קושי בזוגיות" },
    { problem_id: "36", alias: "הפרעות אכילה" },
    { problem_id: "36", alias: "הפרעת אכילה" },
    { problem_id: "20", alias: "קשיי קשב וריכוז" },
    { problem_id: "16", alias: "מתח הורי" },
    { problem_id: "16", alias: "קשיים בהורות" },
    { problem_id: "21", alias: "הספקטרום האוטיסטי" },
    { problem_id: "17", alias: "קשיים ביצירת קשרים חברתיים" },
    { problem_id: "11", alias: "טראומה מינית" },
    { problem_id: "37", alias: "דימוי גוף" },
    { problem_id: "17", alias: "בדידות" },
    { problem_id: "4", alias: "קשיים בוויסות רגשי" },
    { problem_id: "16", alias: "קונפליקטים בין הורים לילדים" },
    { problem_id: "10", alias: "הפרעת דחק פוסט טראומטית" },
    { problem_id: "5", alias: "חוסר ביטחון" },
    { problem_id: "16", alias: "טיפול משפחתי" },
    { problem_id: "16", alias: "ילד במשבר" },
    { problem_id: "24", alias: "התפרצויות והתנהגות מאתגרת" },
    { problem_id: "40", alias: "נדודי שינה" },
    { problem_id: "17", alias: "בדידות וקשיים חברתיים" },
    { problem_id: "12", alias: "קשר פוגעני" },
    { problem_id: "1", alias: "פחדים אצל ילדים" },
    { problem_id: "40", alias: "קושי בהירדמות" },
    { problem_id: "1", alias: "חרדה ודאגנות" },
    { problem_id: "14", alias: "הסתגלות לפרישה" },
    { problem_id: "35", alias: "בחירת קריירה" },
    { problem_id: "15", alias: "הכנה לנישואין" },
    { problem_id: "2", alias: "דיכאון ושינויים במצב הרוח" },
    { problem_id: "40", alias: "יקיצות מרובות" },
    { problem_id: "10", alias: "התמודדות לאחר אירוע ביטחוני" },
    { problem_id: "40", alias: "הפרעות שינה" },
    { problem_id: "16", alias: "התמודדות עם גירושי הורים" },
    { problem_id: "40", alias: "בעיות שינה" },
    { problem_id: "12", alias: "אלימות" },
    { problem_id: "1", alias: "חרדה ופחדים" },
    { problem_id: "12", alias: "התעללות פיזית" },
    { problem_id: "15", alias: "קנאה וחוסר אמון" },
    { problem_id: "16", alias: "יחסים במשפחה" },
    { problem_id: "12", alias: "אלימות במשפחה" },
    { problem_id: "16", alias: "יחסים בין אחים" },
    { problem_id: "13", alias: "אובדן ואבל" },
    { problem_id: "33", alias: "לחץ לימודי" },
    { problem_id: "15", alias: "תלות רגשית" },
    { problem_id: "19", alias: "טיפול מיני" },
    { problem_id: "15", alias: "זוגיות ומערכות יחסים" },
    { problem_id: "16", alias: "גירושי הורים" },
    { problem_id: "40", alias: "אינסומניה" },
    { problem_id: "16", alias: "קשיים בין אחים" },
    { problem_id: "57", alias: "שימוש באלכוהול" },
    { problem_id: "40", alias: "שינה לא רציפה" },
    { problem_id: "9", alias: "משמעות ואיכות חיים" },
    { problem_id: "15", alias: "קושי ביצירת קשר" },
    { problem_id: "12", alias: "מערכת יחסים פוגענית" },
    { problem_id: "16", alias: "הורות משותפת" },
    { problem_id: "15", alias: "קונפליקטים חוזרים" },
    { problem_id: "15", alias: "בגידה ואובדן אמון" },
    { problem_id: "1", alias: "חרדה ולחץ" },
    { problem_id: "40", alias: "הפרעת שינה" },
    { problem_id: "4", alias: "התפרצויות וכעסים" },
    { problem_id: "40", alias: "קושי להירדם" },
    { problem_id: "34", alias: "שחיקה ולחץ בעבודה" },
    { problem_id: "19", alias: "קשיים מיניים" },
    { problem_id: "16", alias: "משפחות משולבות" },
    { problem_id: "16", alias: "מריבות וקונפליקטים במשפחה" },
    { problem_id: "1", alias: "חרדת מבחנים" },
    { problem_id: "17", alias: "קשיים חברתיים ובדידות" },
    { problem_id: "22", alias: "עיכוב התפתחותי" },
    { problem_id: "14", alias: "קשיי הסתגלות" },
    { problem_id: "16", alias: "גירושין ומשפחה בתהליך שינוי" },
    { problem_id: "14", alias: "עצמאות ומעבר לחיים בוגרים" },
    { problem_id: "19", alias: "אינטימיות ומיניות" },
    { problem_id: "12", alias: "מערכות יחסים פוגעניות" },
    { problem_id: "40", alias: "קשיי שינה" },
    { problem_id: "1", alias: "פחד מטיסה" },
    { problem_id: "12", alias: "אלימות בזוגיות" },
    { problem_id: "14", alias: "שינוי משמעותי בחיים" },
    { problem_id: "12", alias: "התעללות רגשית" },
    { problem_id: "2", alias: "דיכאון ומצב רוח ירוד" },
    { problem_id: "19", alias: "קשיים באינטימיות" },
    { problem_id: "16", alias: "יחסים עם ההורים" },
    { problem_id: "19", alias: "קשיים במיניות" },
    { problem_id: "12", alias: "זוגיות פוגענית" },
    { problem_id: "14", alias: "שינויי חיים" },
    { problem_id: "57", alias: "עישון" },
    { problem_id: "16", alias: "התמודדות עם ילד במשבר" },
    { problem_id: "7", alias: "הפרעה דו קוטבית" },
    { problem_id: "7", alias: "הפרעה ביפולרית" },
    { problem_id: "7", alias: "ביפולר" },
    { problem_id: "7", alias: "מאניה דפרסיה" },
    { problem_id: "8", alias: "פסיכוזה" },
    { problem_id: "8", alias: "הפרעה פסיכוטית" },
    { problem_id: "8", alias: "הפרעות פסיכוטיות" },
    { problem_id: "8", alias: "מצב פסיכוטי" },
    { problem_id: "18", alias: "תקשורת בין אישית" },
    { problem_id: "18", alias: "קשיים בתקשורת בין אישית" },
    { problem_id: "18", alias: "קושי לבטא רגשות" },
    { problem_id: "18", alias: "קושי בביטוי רגשי" },
    { problem_id: "18", alias: "ביטוי רגשי" },
    { problem_id: "23", alias: "ויסות חושי" },
    { problem_id: "23", alias: "עיבוד חושי" },
    { problem_id: "23", alias: "קשיים בוויסות חושי" },
    { problem_id: "23", alias: "קשיי עיבוד חושי" },
    { problem_id: "23", alias: "רגישות חושית" },
    { problem_id: "24", alias: "התנהגות מאתגרת" },
    { problem_id: "24", alias: "קשיי התנהגות" },
    { problem_id: "24", alias: "בעיות התנהגות" },
    { problem_id: "24", alias: "התנהגות מתנגדת" },
    { problem_id: "25", alias: "לקויות למידה" },
    { problem_id: "25", alias: "קשיי למידה" },
    { problem_id: "25", alias: "דיסלקציה" },
    { problem_id: "25", alias: "דיסגרפיה" },
    { problem_id: "25", alias: "דיסקלקוליה" },
    { problem_id: "26", alias: "קשיי קואורדינציה" },
    { problem_id: "26", alias: "קואורדינציה מוטורית" },
    { problem_id: "26", alias: "עיכוב מוטורי" },
    { problem_id: "26", alias: "הפרעה התפתחותית בקואורדינציה" },
    { problem_id: "26", alias: "DCD" },
    { problem_id: "27", alias: "קשיי שפה" },
    { problem_id: "27", alias: "עיכוב שפתי" },
    { problem_id: "27", alias: "התפתחות שפה" },
    { problem_id: "27", alias: "קושי בהבנת שפה" },
    { problem_id: "27", alias: "קושי בהבעת שפה" },
    { problem_id: "28", alias: "קשיי היגוי" },
    { problem_id: "28", alias: "הפרעת היגוי" },
    { problem_id: "28", alias: "שיבושי היגוי" },
    { problem_id: "28", alias: "היגוי לא ברור" },
    { problem_id: "28", alias: "דיסארתריה" },
    { problem_id: "29", alias: "גמגום" },
    { problem_id: "29", alias: "הפרעת שטף דיבור" },
    { problem_id: "29", alias: "קשיי שטף בדיבור" },
    { problem_id: "29", alias: "חוסר שטף בדיבור" },
    { problem_id: "30", alias: "הפרעת קול" },
    { problem_id: "30", alias: "הפרעות קול" },
    { problem_id: "30", alias: "קשיי קול" },
    { problem_id: "30", alias: "דיספוניה" },
    { problem_id: "31", alias: "שיקום שמיעתי" },
    { problem_id: "31", alias: "ירידה בשמיעה" },
    { problem_id: "31", alias: "לקות שמיעה" },
    { problem_id: "31", alias: "קשיי שמיעה" },
    { problem_id: "31", alias: "אימון שמיעתי" },
    { problem_id: "32", alias: "קשיי בליעה" },
    { problem_id: "32", alias: "הפרעת בליעה" },
    { problem_id: "32", alias: "דיספגיה" },
    { problem_id: "32", alias: "קשיי לעיסה" },
    { problem_id: "32", alias: "אכילה תפקודית" },
    { problem_id: "38", alias: "הרגלי אכילה" },
    { problem_id: "38", alias: "שינוי הרגלי אכילה" },
    { problem_id: "38", alias: "שיפור הרגלי אכילה" },
    { problem_id: "38", alias: "תזונה והרגלי אכילה" },
    { problem_id: "39", alias: "תזונה רפואית" },
    { problem_id: "39", alias: "תזונה במצבים רפואיים" },
    { problem_id: "39", alias: "תזונה במחלות כרוניות" },
    { problem_id: "39", alias: "התאמת תזונה למצב רפואי" },
    { problem_id: "41", alias: "כאבי שריר ושלד" },
    { problem_id: "41", alias: "כאב שריר ושלד" },
    { problem_id: "41", alias: "כאבי גב" },
    { problem_id: "41", alias: "כאבי צוואר" },
    { problem_id: "41", alias: "כאבי מפרקים" },
    { problem_id: "42", alias: "כאב כרוני" },
    { problem_id: "42", alias: "כאבים כרוניים" },
    { problem_id: "42", alias: "כאב מתמשך" },
    { problem_id: "42", alias: "כאב ממושך" },
    { problem_id: "43", alias: "שיקום אורתופדי" },
    { problem_id: "43", alias: "שיקום לאחר ניתוח אורתופדי" },
    { problem_id: "43", alias: "שיקום אחרי ניתוח אורתופדי" },
    { problem_id: "43", alias: "שיקום לאחר שבר" },
    { problem_id: "44", alias: "שיקום נוירולוגי" },
    { problem_id: "44", alias: "שיקום לאחר שבץ" },
    { problem_id: "44", alias: "שיקום אחרי שבץ" },
    { problem_id: "44", alias: "שיקום לאחר אירוע מוחי" },
    { problem_id: "44", alias: "שיקום לאחר פגיעה מוחית" },
    { problem_id: "45", alias: "קשיי ניידות" },
    { problem_id: "45", alias: "בעיות ניידות" },
    { problem_id: "45", alias: "קשיי שיווי משקל" },
    { problem_id: "45", alias: "בעיות שיווי משקל" },
    { problem_id: "45", alias: "מניעת נפילות" },
    { problem_id: "46", alias: "רצפת אגן" },
    { problem_id: "46", alias: "שיקום רצפת אגן" },
    { problem_id: "46", alias: "חולשת רצפת אגן" },
    { problem_id: "46", alias: "תפקוד רצפת אגן" },
    { problem_id: "47", alias: "שיקום לב ריאה" },
    { problem_id: "47", alias: "שיקום לבבי" },
    { problem_id: "47", alias: "שיקום ריאתי" },
    { problem_id: "47", alias: "שיקום נשימתי" },
    { problem_id: "48", alias: "פציעות ספורט" },
    { problem_id: "48", alias: "שיקום ספורט" },
    { problem_id: "48", alias: "שיקום מפציעת ספורט" },
    { problem_id: "48", alias: "חזרה לפעילות ספורטיבית" },
    { problem_id: "49", alias: "תפקוד יומיומי" },
    { problem_id: "49", alias: "קשיים בתפקוד יומיומי" },
    { problem_id: "49", alias: "עצמאות בתפקוד" },
    { problem_id: "49", alias: "פעילויות היום יום" },
    { problem_id: "49", alias: "ADL" },
    { problem_id: "50", alias: "שיקום קוגניטיבי" },
    { problem_id: "50", alias: "שיקום קוגניטיבי לאחר פגיעה מוחית" },
    { problem_id: "50", alias: "שיקום קוגניטיבי לאחר אירוע מוחי" },
    { problem_id: "50", alias: "אימון קוגניטיבי שיקומי" },
    { problem_id: "51", alias: "מוטוריקה עדינה" },
    { problem_id: "51", alias: "קשיים במוטוריקה עדינה" },
    { problem_id: "51", alias: "גרפומוטוריקה" },
    { problem_id: "51", alias: "קשיי גרפומוטוריקה" },
    { problem_id: "52", alias: "ירידה קוגניטיבית" },
    { problem_id: "52", alias: "דמנציה" },
    { problem_id: "52", alias: "אלצהיימר" },
    { problem_id: "52", alias: "הפרעה נוירוקוגניטיבית" },
    { problem_id: "52", alias: "ירידה בתפקוד הקוגניטיבי" },
    { problem_id: "53", alias: "היריון ולידה" },
    { problem_id: "53", alias: "הריון ולידה" },
    { problem_id: "53", alias: "משכב לידה" },
    { problem_id: "53", alias: "תקופה לאחר לידה" },
    { problem_id: "53", alias: "התאוששות לאחר לידה" },
    { problem_id: "54", alias: "הנקה" },
    { problem_id: "54", alias: "קשיי הנקה" },
    { problem_id: "54", alias: "בעיות בהנקה" },
    { problem_id: "54", alias: "ייעוץ הנקה" },
    { problem_id: "54", alias: "ליווי הנקה" },
    { problem_id: "55", alias: "התמודדות עם טיפולי פוריות" },
    { problem_id: "55", alias: "ליווי בטיפולי פוריות" },
    { problem_id: "55", alias: "מסע פוריות" },
    { problem_id: "55", alias: "קשיים סביב פוריות" },
    { problem_id: "55", alias: "ליווי סביב פוריות" },
    { problem_id: "60", alias: "התמודדות עם מחלה כרונית" },
    { problem_id: "60", alias: "הסתגלות למחלה כרונית" },
    { problem_id: "60", alias: "חיים עם מחלה כרונית" },
    { problem_id: "60", alias: "התמודדות עם מצב רפואי כרוני" },
    { problem_id: "61", alias: "שיקום רפואי" },
    { problem_id: "61", alias: "שיקום לאחר אשפוז" },
    { problem_id: "61", alias: "שיקום אחרי אשפוז" },
    { problem_id: "61", alias: "שיקום לאחר מחלה" },
    { problem_id: "61", alias: "שיקום לאחר ניתוח" },
    { problem_id: "62", alias: "הסתגלות למוגבלות" },
    { problem_id: "62", alias: "התמודדות עם מוגבלות" },
    { problem_id: "62", alias: "חיים עם מוגבלות" },
    { problem_id: "62", alias: "הסתגלות לשינוי תפקודי" },
    { problem_id: "62", alias: "התמודדות עם שינוי תפקודי" },
  ],
};
