import { tokenizeHebrew, lightNormalizeHebrew, foldSofit } from "../src/lib/hebrew-normalizer";
console.log("norm:", JSON.stringify(lightNormalizeHebrew("אשמח לקבל אישה מטפלת")));
console.log("toks:", tokenizeHebrew("אשמח לקבל אישה מטפלת"));
console.log("norm2:", JSON.stringify(lightNormalizeHebrew("אני מחפש פסיכולוגית בתל אביב")));
console.log("toks2:", tokenizeHebrew("אני מחפש פסיכולוגית בתל אביב"));
console.log("norm3:", JSON.stringify(lightNormalizeHebrew("אני מחפש מאבחן קשב")));
console.log("toks3:", tokenizeHebrew("אני מחפש מאבחן קשב"));
console.log("fold מאבחן:", foldSofit("מאבחן"));
console.log("norm4:", JSON.stringify(lightNormalizeHebrew("אישה גבר פסיכולוג")));
console.log("toks4:", tokenizeHebrew("אישה גבר פסיכולוג"));
console.log("toks5:", tokenizeHebrew("יעל כהן"));
console.log("normprefix:", lightNormalizeHebrew("אני מחפש"), "|", foldSofit("אני מחפש"));
