/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TherapyInformationRouteImport } from './routes/therapy-information'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfilePreviewDemoRouteImport } from './routes/profile-preview-demo'
import { Route as ForTherapistsRouteImport } from './routes/for-therapists'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TherapistsSlugRouteImport } from './routes/therapists.$slug'
import { Route as ProblemsSlugRouteImport } from './routes/problems.$slug'
import { Route as AuthenticatedNewProfileRouteImport } from './routes/_authenticated/new-profile'
import { Route as AuthenticatedClaimRouteImport } from './routes/_authenticated/claim'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'

const TherapyInformationRoute = TherapyInformationRouteImport.update({
  id: '/therapy-information',
  path: '/therapy-information',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilePreviewDemoRoute = ProfilePreviewDemoRouteImport.update({
  id: '/profile-preview-demo',
  path: '/profile-preview-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ForTherapistsRoute = ForTherapistsRouteImport.update({
  id: '/for-therapists',
  path: '/for-therapists',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TherapistsSlugRoute = TherapistsSlugRouteImport.update({
  id: '/therapists/$slug',
  path: '/therapists/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsSlugRoute = ProblemsSlugRouteImport.update({
  id: '/problems/$slug',
  path: '/problems/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNewProfileRoute = AuthenticatedNewProfileRouteImport.update({
  id: '/new-profile',
  path: '/new-profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClaimRoute = AuthenticatedClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/for-therapists': typeof ForTherapistsRoute
  '/profile-preview-demo': typeof ProfilePreviewDemoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/therapy-information': typeof TherapyInformationRoute
  '/account': typeof AuthenticatedAccountRoute
  '/claim': typeof AuthenticatedClaimRoute
  '/new-profile': typeof AuthenticatedNewProfileRoute
  '/problems/$slug': typeof ProblemsSlugRoute
  '/therapists/$slug': typeof TherapistsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/for-therapists': typeof ForTherapistsRoute
  '/profile-preview-demo': typeof ProfilePreviewDemoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/therapy-information': typeof TherapyInformationRoute
  '/account': typeof AuthenticatedAccountRoute
  '/claim': typeof AuthenticatedClaimRoute
  '/new-profile': typeof AuthenticatedNewProfileRoute
  '/problems/$slug': typeof ProblemsSlugRoute
  '/therapists/$slug': typeof TherapistsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/for-therapists': typeof ForTherapistsRoute
  '/profile-preview-demo': typeof ProfilePreviewDemoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/therapy-information': typeof TherapyInformationRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/claim': typeof AuthenticatedClaimRoute
  '/_authenticated/new-profile': typeof AuthenticatedNewProfileRoute
  '/problems/$slug': typeof ProblemsSlugRoute
  '/therapists/$slug': typeof TherapistsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/for-therapists'
    | '/profile-preview-demo'
    | '/reset-password'
    | '/search'
    | '/sitemap.xml'
    | '/therapy-information'
    | '/account'
    | '/claim'
    | '/new-profile'
    | '/problems/$slug'
    | '/therapists/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/for-therapists'
    | '/profile-preview-demo'
    | '/reset-password'
    | '/search'
    | '/sitemap.xml'
    | '/therapy-information'
    | '/account'
    | '/claim'
    | '/new-profile'
    | '/problems/$slug'
    | '/therapists/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/for-therapists'
    | '/profile-preview-demo'
    | '/reset-password'
    | '/search'
    | '/sitemap.xml'
    | '/therapy-information'
    | '/_authenticated/account'
    | '/_authenticated/claim'
    | '/_authenticated/new-profile'
    | '/problems/$slug'
    | '/therapists/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForTherapistsRoute: typeof ForTherapistsRoute
  ProfilePreviewDemoRoute: typeof ProfilePreviewDemoRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TherapyInformationRoute: typeof TherapyInformationRoute
  ProblemsSlugRoute: typeof ProblemsSlugRoute
  TherapistsSlugRoute: typeof TherapistsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/therapy-information': {
      id: '/therapy-information'
      path: '/therapy-information'
      fullPath: '/therapy-information'
      preLoaderRoute: typeof TherapyInformationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-preview-demo': {
      id: '/profile-preview-demo'
      path: '/profile-preview-demo'
      fullPath: '/profile-preview-demo'
      preLoaderRoute: typeof ProfilePreviewDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-therapists': {
      id: '/for-therapists'
      path: '/for-therapists'
      fullPath: '/for-therapists'
      preLoaderRoute: typeof ForTherapistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/therapists/$slug': {
      id: '/therapists/$slug'
      path: '/therapists/$slug'
      fullPath: '/therapists/$slug'
      preLoaderRoute: typeof TherapistsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems/$slug': {
      id: '/problems/$slug'
      path: '/problems/$slug'
      fullPath: '/problems/$slug'
      preLoaderRoute: typeof ProblemsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/new-profile': {
      id: '/_authenticated/new-profile'
      path: '/new-profile'
      fullPath: '/new-profile'
      preLoaderRoute: typeof AuthenticatedNewProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/claim': {
      id: '/_authenticated/claim'
      path: '/claim'
      fullPath: '/claim'
      preLoaderRoute: typeof AuthenticatedClaimRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedClaimRoute: typeof AuthenticatedClaimRoute
  AuthenticatedNewProfileRoute: typeof AuthenticatedNewProfileRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedClaimRoute: AuthenticatedClaimRoute,
  AuthenticatedNewProfileRoute: AuthenticatedNewProfileRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForTherapistsRoute: ForTherapistsRoute,
  ProfilePreviewDemoRoute: ProfilePreviewDemoRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TherapyInformationRoute: TherapyInformationRoute,
  ProblemsSlugRoute: ProblemsSlugRoute,
  TherapistsSlugRoute: TherapistsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
